version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.2.0
  aws-ecs: circleci/aws-ecs@0.0.10

jobs:
  build:
    docker: 
      - image: golang:1.13-alpine
    working_directory: /tmp/project
    steps:
      - run: apk add --no-cache git mercurial openssh gcc build-base
      - checkout
      - run: printf "[url \"git@github.com:\"]\n\tinsteadOf = https://github.com/" >> /root/.gitconfig
      - run: go mod download
      - run: go get gotest.tools/gotestsum
      - run: go mod vendor
      - run: mv /tmp/project/vendor/github.com/tantralabs/yantra/ca-certificates.crt /tmp/project/ca-certificates.crt
      - run: gotestsum --junitfile results.xml
      - run: mkdir /tmp/project/tests
      - run: mv /tmp/project/results.xml /tmp/project/tests/results.xml
      - store_test_results:
          path: /tmp/project/tests
  
workflows:
  build_test_deploy:
    jobs: 
      - build:
          context: AWS-ECS
